### ISSUE TITLE
Дублювання стилів

### ISSUE THREAD

**Issue by RBV1** [OleksiiLavrov/Grovemade#2]
https://github.com/OleksiiLavrov/Project/blob/ff7d6530c4ecbe64279ed8f2715f76787d92ee42/css/firstbox.css#L35

Тут, наче, по всіх файлах один і той самий код для `body` описаний. Давай краще всі стилі щодо `body` будуть в якось одному файлі(css у нас каскадний воно буде діяти, якщо його водному місці написати). 

п.с. і давай краще не обмежувати body, нехай цей елемент буде собі завжди на всю ширину, можемо обмежувати секції. Наприклад, можна сторити клас `.container` якому понаписувати стилів у файлі з назвою, наприклад, `layout.css`:(код скопіював з `bootsrap` для прикладу)

```css
.container {
  padding: 0 15px;
}

@media (min-width: 575.98px){
  .container {
    max-width: 540px;
    margin: auto;
    padding: 0;
  }
}

@media (min-width: 767.98px){
  .container {
    max-width: 720px;	
  }
}

@media (min-width: 991.98px) {
  .container {
    max-width: 960px;
  }
}

@media (min-width: 1199.98px){
  .container {
    max-width: 1140px;
  }
}
```
